meteo_api_schema = {
    "type": "object",
    "properties": {
        "latitude": {"type": "number"},
        "longitude": {"type": "number"},
        "generationtime_ms": {"type": "number"},
        "utc_offset_seconds": {"type": "number"},
        "timezone": {"type": "string"},
        "timezone_abbreviation": {"type": "string"},
        "elevation": {"type": "number"},
        "daily_units": {
            "type": "object",
            "properties": {
                "time": {"type": "string"},
                "temperature_2m_mean_CMCC_CM2_VHR4": {"type": "string"},
                "precipitation_sum_CMCC_CM2_VHR4": {"type": "string"},
                "soil_moisture_0_to_10cm_mean_CMCC_CM2_VHR4": {"type": "string"},
                "temperature_2m_mean_FGOALS_f3_H": {"type": "string"},
                "precipitation_sum_FGOALS_f3_H": {"type": "string"},
                "soil_moisture_0_to_10cm_mean_FGOALS_f3_H": {"type": "string"},
                "temperature_2m_mean_HiRAM_SIT_HR": {"type": "string"},
                "precipitation_sum_HiRAM_SIT_HR": {"type": "string"},
                "soil_moisture_0_to_10cm_mean_HiRAM_SIT_HR": {"type": "string"},
                "temperature_2m_mean_MRI_AGCM3_2_S": {"type": "string"},
                "precipitation_sum_MRI_AGCM3_2_S": {"type": "string"},
                "soil_moisture_0_to_10cm_mean_MRI_AGCM3_2_S": {"type": "string"},
                "temperature_2m_mean_EC_Earth3P_HR": {"type": "string"},
                "precipitation_sum_EC_Earth3P_HR": {"type": "string"},
                "soil_moisture_0_to_10cm_mean_EC_Earth3P_HR": {"type": "string"},
                "temperature_2m_mean_MPI_ESM1_2_XR": {"type": "string"},
                "precipitation_sum_MPI_ESM1_2_XR": {"type": "string"},
                "soil_moisture_0_to_10cm_mean_MPI_ESM1_2_XR": {"type": "string"},
                "temperature_2m_mean_NICAM16_8S": {"type": "string"},
                "precipitation_sum_NICAM16_8S": {"type": "string"},
                "soil_moisture_0_to_10cm_mean_NICAM16_8S": {"type": "string"},
            },
        },
        "daily": {
            "type": "object",
            "time": "array",
            "items": {"type": "string"},
            "temperature_2m_mean_CMCC_CM2_VHR4": "array",
            "items": {"type": "number"},
            "precipitation_sum_CMCC_CM2_VHR4": "array",
            "items": {"type": "number"},
            "soil_moisture_0_to_10cm_mean_CMCC_CM2_VHR4": "array",
            "items": {"type": "number"},
            "temperature_2m_mean_FGOALS_f3_H": "array",
            "items": {"type": "number"},
            "precipitation_sum_FGOALS_f3_H": "array",
            "items": {"type": "number"},
            "soil_moisture_0_to_10cm_mean_FGOALS_f3_H": "array",
            "items": {"type": "number"},
            "temperature_2m_mean_HiRAM_SIT_HR": "array",
            "items": {"type": "number"},
            "precipitation_sum_HiRAM_SIT_HR": "array",
            "items": {"type": "number"},
            "soil_moisture_0_to_10cm_mean_HiRAM_SIT_HR": "array",
            "items": {"type": "number"},
            "temperature_2m_mean_MRI_AGCM3_2_S": "array",
            "items": {"type": "number"},
            "precipitation_sum_MRI_AGCM3_2_S": "array",
            "items": {"type": "number"},
            "soil_moisture_0_to_10cm_mean_MRI_AGCM3_2_S": "array",
            "items": {"type": "number"},
            "temperature_2m_mean_EC_Earth3P_HR": "array",
            "items": {"type": "number"},
            "precipitation_sum_EC_Earth3P_HR": "array",
            "items": {"type": "number"},
            "soil_moisture_0_to_10cm_mean_EC_Earth3P_HR": "array",
            "items": {"type": "number"},
            "temperature_2m_mean_MPI_ESM1_2_XR": "array",
            "items": {"type": "number"},
            "precipitation_sum_MPI_ESM1_2_XR": "array",
            "items": {"type": "number"},
            "soil_moisture_0_to_10cm_mean_MPI_ESM1_2_XR": "array",
            "items": {"type": "number"},
            "temperature_2m_mean_NICAM16_8S": "array",
            "items": {"type": "number"},
            "precipitation_sum_NICAM16_8S": "array",
            "items": {"type": "number"},
            "soil_moisture_0_to_10cm_mean_NICAM16_8S": "array",
            "items": {"type": "number"},
        },
    },
}
